# Generated by Django 3.1 on 2023-07-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('a_f', models.TextField(blank=True, null=True)),
                ('b_f', models.TextField(blank=True, null=True)),
                ('c_f', models.TextField(blank=True, null=True)),
                ('d_f', models.TextField(blank=True, null=True)),
                ('e_f', models.TextField(blank=True, null=True)),
                ('f_f', models.TextField(blank=True, null=True)),
                ('g_f', models.TextField(blank=True, null=True)),
                ('h_f', models.TextField(blank=True, null=True)),
                ('i_f', models.TextField(blank=True, null=True)),
                ('j_f', models.TextField(blank=True, null=True)),
                ('k_f', models.TextField(blank=True, null=True)),
                ('l_f', models.TextField(blank=True, null=True)),
                ('m_f', models.TextField(blank=True, null=True)),
                ('n_f', models.TextField(blank=True, null=True)),
                ('o_f', models.TextField(blank=True, null=True)),
                ('p_f', models.TextField(blank=True, null=True)),
                ('q_f', models.TextField(blank=True, null=True)),
                ('r_f', models.TextField(blank=True, null=True)),
                ('s_f', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True, verbose_name='更新時間')),
            ],
        ),
    ]
