# Generated by Django 3.1 on 2023-07-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20230713_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='fields',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='原名稱')),
                ('new_name', models.TextField(blank=True, null=True, verbose_name='欄位名稱')),
                ('hide', models.CharField(blank=True, max_length=5, null=True, verbose_name='隱藏欄位')),
                ('create_date', models.DateTimeField(verbose_name='建立日期')),
            ],
            options={
                'db_table': 'form_fields',
            },
        ),
        migrations.AlterModelTable(
            name='blist',
            table='form_blist',
        ),
    ]
